# Generated by Django 5.2.3 on 2025-06-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signature_image",
            field=models.ImageField(blank=True, null=True, upload_to="signatures/"),
        ),
    ]
