# Generated by Django 5.1.6 on 2025-05-27 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_actionlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="highcosttransportrequest",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="highcost_requests",
                to="core.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="requesters_car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to="core.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="refuelingrequest",
            name="requesters_car",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="refueling_requests",
                to="core.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="transportrequest",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="transport_requests",
                to="core.vehicle",
            ),
        ),
    ]
