# Generated by Django 5.2.1 on 2025-06-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_servicerequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicerequest",
            name="current_approver_role",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Employee"),
                    (2, "Department Manager"),
                    (3, "Finance Manager"),
                    (4, "Transport Manager"),
                    (5, "CEO"),
                    (6, "Driver"),
                    (7, "System Admin"),
                    (8, "General System Excuter"),
                    (9, "Budget Manager"),
                ],
                default=4,
            ),
        ),
    ]
