# Generated by Django 5.2.3 on 2025-06-23 05:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_otpcode"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="otpcode",
            constraint=models.UniqueConstraint(
                fields=("user",), name="unique_otp_per_user"
            ),
        ),
    ]
