# Generated by Django 5.2.3 on 2025-07-02 05:51

import django.utils.timezone
from django.db import migrations, models
import uuid
def assign_unique_chassis_and_motor(apps, schema_editor):
    Vehicle = apps.get_model('core', 'Vehicle')
    for vehicle in Vehicle.objects.all():
        vehicle.chassis_number = str(uuid.uuid4())
        vehicle.motor_number = str(uuid.uuid4())
        vehicle.save()
class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_otpcode_unique_otp_per_user"),
    ]

    operations = [
         migrations.AddField(
            model_name="vehicle",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
         migrations.AddField(
            model_name="vehicle",
            name="chassis_number",
            field=models.CharField(max_length=100, unique=True, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="motor_number",
            field=models.CharField(max_length=100, unique=True, null=True, blank=True),
        ),
        migrations.RunPython(assign_unique_chassis_and_motor),
        migrations.AlterField(
            model_name="vehicle",
            name="chassis_number",
            field=models.CharField(max_length=100, unique=True, null=False, blank=False),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="motor_number",
            field=models.CharField(max_length=100, unique=True, null=False, blank=False),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Used for activate and deactivate vehicles."
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Used for soft delete of vehicles."
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="libre_number",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
       
        migrations.AddField(
            model_name="vehicle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
