# Generated by Django 5.2.3 on 2025-07-02 05:53

import django.utils.timezone
from django.db import migrations, models

def assign_unique_libre_number(apps, schema_editor):
    import uuid
    Vehicle = apps.get_model('core', 'Vehicle')
    for vehicle in Vehicle.objects.all():
        vehicle.libre_number = str(uuid.uuid4())
        vehicle.save()
class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_vehicle_chassis_number_vehicle_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="libre_number",
            field=models.CharField(
                 max_length=100, unique=True, null=True, blank=True,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(assign_unique_libre_number),
        migrations.AlterField(
        model_name="vehicle",
        name="libre_number",
        field=models.CharField(max_length=100, unique=True, null=False, blank=False),
    ),
     migrations.AddField(
            model_name="vehicle",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]