# Generated by Django 5.2.3 on 2025-07-02 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_alter_vehicle_libre_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vehicle",
            name="chassis_number",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="is_deleted",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="libre_number",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="motor_number",
        ),
        migrations.RemoveField(
            model_name="vehicle",
            name="updated_at",
        ),
    ]
