# Generated by Django 5.2.3 on 2025-07-02 07:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_remove_vehicle_chassis_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="chassis_number",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Used for activate and deactivate vehicles."
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="Used for soft delete of vehicles."
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="libre_number",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="motor_number",
            field=models.CharField(
                default=django.utils.timezone.now, max_length=100, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
