# Generated by Django 5.2.3 on 2025-07-10 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0003_user_signature_image"),
        ("core", "0032_vehicle_chassis_number_vehicle_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vehicles",
                to="auth_app.department",
            ),
        ),
    ]
