# Generated by Django 5.2.3 on 2025-07-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_vehicle_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="drivers_location",
            field=models.CharField(
                blank=True,
                help_text="Location of the driver for rented vehicles.",
                max_length=255,
                null=True,
            ),
        ),
    ]
