# Generated by Django 5.2.3 on 2025-07-17 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_vehicle_chassis_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="highcosttransportrequest",
            name="employee_list_file",
            field=models.FileField(
                blank=True,
                help_text="Upload a file containing the list of employees for this request.",
                null=True,
                upload_to="highcost_employee_lists/",
            ),
        ),
    ]
